// import {upload} from "../utils/fileUploader";

export const dataObj = {

    AGENTIDSTART: 'QTA',
    STAFFIDSTART: 'QTS',
    SUBAGENTIDSTART: 'QTSA',
    BONUSSTARTID: 'QTB',
    CMSSTARTID: 'QTC',
    DEPOSITSTARTID: 'QTD',
    LEDGERSTARTID: 'QTLE',
    LOANSTARTID: 'QTLO',
    REFUNDSTARTID: 'QTRF',
    REISSUESTART: 'QTRE',
    SUBAGENTLEDGERID: 'QTSLE',
    VOIDSTARTID: 'QTV',
    TICKETID: 'QT',
    WITHDRAWSTART: 'QTW',
    ADMINSTARTID: 'QTAD',
    BOOKINGSTARTID: 'QTBK',
    CURRENCY_START_ID: 'FFTB',
    A_CMS: 'ACMS',
    SEARCH: 'QTS',
    PASSENGERS_START_ID: 'QTP',
    VENDOR: 'QTV'

}

export const Tables = {
    AGENT: 'agent',
    STAFF: 'stafflist',
    SUBAGENT: 'subagent',
    BONUS: 'bonus',
    CMS: 'cms',
    DEPOSIT: 'deposit',
    LEDGER: 'ledger',
    LOAN: 'loan',
    PASSENGERS: 'passengers',
    REFUND: 'refund',
    REISSUE: 'reissue',
    SUBAGENTLEDGER: 'subagent_ledger',
    VOID: 'void',
    TICKET: 'ticketed',
    WITHDRAW: 'withdraw',
    ADMIN: 'admin',
    BOOKING: 'booking',
    ROUTERS: 'routes',
    WINGS: 'wings',
    INVENTORY: 'inventory',
    CURRENCY: 'currencyManagement',
    A_CMS: 'agentCMS',
    SEARCH: 'search_history',
    BOOKING_AIRLINES: 'bookingAirlines',
    BOOKING_AIRPORTS: 'bookingAirports',
    BOOKING_PRICES: 'bookingPrices',
    BOOKING_CARRIERS: 'bookingCarriers',
    BOOKING_SEGMENTS: 'bookingSegments',
    BOOKING_FARES: 'bookingFares',
    BOOKING_BAG_INFO: 'bookingBagInfo',
    BOOKING_FLIGHTS: 'bookingFlights',
    API_KEY: 'apiKey',
    AGENT_DOC: 'agentDoc',
    BOOKING_ACTIVITY_LOG: 'bookingActivityLog',
    BOOKING_CREDIT_INFO: 'bookingCreditInfo',
    AIRLINES: 'airlines',
    AIRPORTS: 'airports',
    SEARCH_HISTORY_VIEW: 'search_history_view',
    AGENT_MARKUP: 'agentMarkup',
    REFUND_BOOKING_LIABILITIES: 'refundBookingLiabilities',
    VENDOR: 'vendor',
    AGENT_BANK: 'agentBank',
    TRAVELER: 'traveler',
    EXPOSED: 'exposed',
    USER_LOGIN_INFO: 'userLoginInfo',
    AIRLINES_DATA: 'airlinesData',
    JSON_DATA_RETRIEVE: 'jsonDataRetrieve',
    BOOKING_PARTIAL: 'bookingPartial',
    BOOKING_PARTIAL_BREAKDOWN: 'bookingPartialBreakDown',
    AGENT_VERIFICATION: 'agentVerification',
    AGENT_OTP: 'agentOtp',
    AGENT_LOGIN_ATTEMPTED: 'agentLoginAttempted',


}

export const IDs = {
    AGENT: 'agentId',
    STAFF: 'staffId',
    SUID: 'suid',
    SUBAGENT: 'subagentId',
    BONUS: 'bonusId',
    CMS: 'cmsId',
    DEPOSIT: 'depositId',
    LEDGER: 'ledgerId',
    LOAN: 'loanId',
    PASSENGERS: 'paxId',
    REFUND: 'refundId',
    REISSUE: 'reissueId',
    SUBAGENTLEDGER: 'subagent_ledgerId',
    VOID: 'voidId',
    TICKET: 'ticketId',
    WITHDRAW: 'withdrawId',
    ADMIN: 'adminId',
    BOOKING: 'bookingId',
    CURRENCYID: 'currencyId',
    A_CMS_ID: 'cmsId',
    SEARCH: 'searchId',
    VENDOR: 'vendorId',


}

export const Constants = {
    PENDING: 'pending',
    B2B: 'B2B',
    PARTIAL_PAYMENT: 'partial Payment',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    UNVERIFIED: 'unverified',
    MALE: 'Male',
    FEMALE: 'Female',
    GENDER_MALE: 'male',
    GENDER_FEMALE: 'female',
    OTHER: 'Other',
    AGENT: 'agent',
    SUBAGENT: 'subagent',
    STAFF: 'staff',
    ACTIVATE: 'activate',
    DEACTIVATE: 'deactivate',
    INTERNATIONAL: 'international',
    DOMESTIC: 'domestic',
    ONEWAY: 'oneWay',
    ROUNDTRIP: 'roundWay',
    RETURN: 'return',
    ROUND_WAY: 'roundWay',
    MULTI_CITY: 'multiCity',
    CASH: 'cash',
    CHEQUE: 'cheque',
    BANK_TRANSFER: 'bankTransfer',
    ECONOMY: 'Economy',
    BUSINESS: 'Business',
    FIRST: 'First',
    HOLD: 'Hold',
    REFUNDED: 'Refunded',
    REFUNDED_ING: 'Refunding',
    REFUND_REQUEST: 'Refund Request',
    REISSUE_REJECTED: 'Reissue Rejected',
    REISSUE_REQUEST: 'Reissue Request',
    REISSUE_IN_PROCESS: 'Reissue In Process',
    REISSUE_PROCESS: 'reissue processing',
    HIBERNATE: 'Hibernate',
    ISSUE_REQUEST: 'Issue Request',
    REISSUED: 'Reissued',
    ADMIN_REISSUE_REJECTED: 'reissue rejected',
    ADMIN_REISSUED: 'reissued',
    TICKETED: 'Ticketed',
    VOID_REJECTED: 'Void Rejected',
    VOIDED: 'Voided',
    VOID_REQUEST: 'Void Request',
    REFUND_REJECTED: 'Refund Rejected',
    ISSUE_REJECTED: 'Issue Rejected',
    CANCELLED: 'Cancelled',
    ADMIN: 'admin',
    ADULT: 'ADT',
    CHILD: 'CNN',
    INFANT: 'INF',
    CO9: 'C09',
    ADULT_NAME: 'adult',
    CHILD_NAME: 'child',
    INFANT_NAME: 'infant',
    USER: 'user',
    LEDGER: 'ledger',
    SUBAGENTLEDGER: 'subagent_ledger',
    UPLOAD: 'uploads',
    APPROVEDBY: 'approvedBy',
    AGENTSEBY: 'agentSetBy',
    ADMINSETBY: 'adminSetBy',
    DEPOSIT: 'deposit',
    SUPER_ADMIN: 'super-admin',
    ADMIN_NID_COPY: 'nidCopy',
    ADMIN_PROFILE_IMAGE: 'img',
    AGENT_NID_COPY: 'nidCopy',
    AGENT_COMPANY_IMAGE: 'companyImage',
    ONE_WAY_SEGMENT: 'oneWay',
    GO_SEGMENT: 'go',
    BACK_SEGMENT: 'back',
    Immediate_Issue: 'Immediate Issue',
    ISSUE: 'Issue',
    INBOUND: 'Inbound',
    OUTBOUND: 'Outbound',
    ZERO: 0,
    ONE: 1,
    TWO: 2,
    THREE: 3,
    THREE_POINT_FIVE: 3.5,
    FOUR: 4,
    FIVE: 5,
    SEVEN: 7,
    TWELVE: 12,
    FIFTEEN: 15,
    SIXTEEN: 16,
    EXPIRE_TIME: 5,
    OTP_LENGTH: 6,
    DOMESTIC_PARTIAL_LIMIT: 20000,
    DOMESTIC_CHARGE: 100,
    INTERNATIONAL_CHARGE: 500,
    SABRE_CASH: 'CA',
    CODE: 'code',
    OBJECT: 'object',
    BANGLADESH: 'BANGLADESH',
    SOTTI: 'sotti',
    SITTI: 'sitti',
    SOTTO: 'sotto',
    ID: 'id',
    PHONE: 'phone',
    EMAIL: 'email',
    PERCENTAGE: 'percentage',
    AMOUNT: 'amount',
    I_MARKUP_TYPE: 'iMarkupType',
    D_MARKUP_TYPE: 'dMarkupType',
    A_MARKUP_TYPE: 'aMarkup',
    REDIS_SEARCH: 'redisSearch',
    BOOKING_ID: 'bookingId',
    SABRE: 'sabre',
    FORGOT: 'forgot',
    DUE: 'due',
    PARTIAL_REFUND: 'refund',
    FORCE_REFUND: 'force refund',
    PAYMENT: 'payment',
    FORCE_PAYMENT: 'force payment',
    OTP_VERIFICATION: "otpVerification",
    VERSION_ONE: 'v1',
    VERSION_TWO: 'v2',
    REQUIRED: 'required',
    TIN_IMAGE: 'tinImage',
    NID_IMAGE: 'nidImage',
    TRADE_IMAGE: 'tradeImage',
    AVIATION_IMAGE: 'aviationImage',
    SIGN_BOARD_IMAGE: 'signboardImage',
    OFFICE_IMAGE_ONE: 'officeImageOne',
    OFFICE_IMAGE_TWO: 'officeImageTwo',
    COMPANY_IMAGE: 'companyImage',
    CUSTOM: 'custom',
    REGEX: 'regex',
    BD_TEAM: 'bdTeam',
    RESERVATION_TEAM: 'reservationTeam',
    ACCOUNT_TEAM: 'accountTeam',
    ADMIN_TEAM: 'adminTeam',
    MANAGEMENT_TEAM: 'managementTeam',
    RESERVATION_OFFICER: 'reservationOfficer',
    BD_OFFICER: 'bdOfficer',
    MANAGEMENT_OFFICER: 'managementOfficer',
    CONTRACTUAL_REJECT: 'contractual reject',
    CONTRACTUAL_VERIFIED: 'contractual verified',
    PHYSICAL_REJECT: 'physical reject',
    PHYSICAL_VERIFIED: 'physical verified',
    RESERVATION_APPROVED: 'reservation approved',
    RESERVATION_REJECT: 'reservation rejected',
    PHYSICAL_VERIFICATION_ATTACHMENT_ONE: 'physicalVerificationAttachmentOne',
    PHYSICAL_VERIFICATION_ATTACHMENT_TWO: 'physicalVerificationAttachmentTwo',
    PHYSICAL_VERIFICATION_ATTACHMENT_THREE: 'physicalVerificationAttachmentThree',
    LOGIN: 'login',
    FORGOT_PASSWORD: 'forgot password',
    ACCOUNT_CREATE_EMAIL_SUBJECT: "Activate your account",
    ACCOUNT_LOGIN_EMAIL_SUBJECT: 'Verify your identity',
    EMAIL_OTP_MESSAGE: 'Please Check your email',
    PHONE_OTP_MESSAGE: 'Please Check your phone',
    PASSWORD_SUCCESS: 'password success',
    PASSWORD_FAILED: 'password failed',
    OTP_SUCCESS: 'otp success',
    OTP_FAILED: 'otp failed',
    FORGOT_PASSWORD_OTP_SUCCESS: 'forgot password otp success',
    FORGOT_PASSWORD_OTP_FAILED: 'forgot password otp failed',
    PASSWORD_OTP_REQUEST: 'password otp request',
    SUCCESS: 'success',
    LOGIN_ATTEMPTED_LIMIT: 6,
    LOCKED: 'locked',
    WRONG_PASSWORD: 'wrong password',
    OTP_INVALID: 'OTP is invalid.',
    DESKTOP: 'desktop',
    MOBILE: 'mobile',
    TABLET: 'tablet',
    OTHERS: 'other',
    TOKEN: 'token',
    SP_TEST: 'SP TEST',
    SABRE_WEB: 'SABRE WEB',
    TICKET_RQ_VERSION: '1.3.0',
    PURCHASE: 'purchase',
    COMPLETE: 'Complete',
    INCOMPLETE: 'Incomplete',
    NOT_PROCESSED: 'NotProcessed',
    UNKNOWN: 'Unknown',
    OTA_AirRulesLLSRQ: 'OTA_AirRulesLLSRQ',
    StructureFareRulesRQ: 'StructureFareRulesRQ',
    GetReservationRQ: 'GetReservationRQ',
    TravelItineraryDivideLLSRQ: 'TravelItineraryDivideLLSRQ',
    EndTransactionLLSRQ: 'EndTransactionLLSRQ',
    YES: 'YES',
    DATE_INDICATOR: 'yyyy-mm-dd',
    DATE_FORMAT: /^\\d{4}-\\d{2}-\\d{2}$/,
    DATE_FORMAT_SABRE: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/,
    DATE_SABRE_INDICATOR: 'yyyy-mm-ddThh:mm:ss',
    DEPARTURE_DATETIME :'departureDateTime',
    DEPARTURE_DATE :'departureDate',
    BOOKING_DATETIME: 'bookingDateTime',
    GALILEO: 'galileo',
    INDIGO:'Indigo',
    REFUNDABLE : 'Refundable',
    NONREFUNDABLE : 'NonRefundable',
    SYSTEM_ONE: 'system001',
    SYSTEM_TWO: 'System002',
    SYSTEM_THREE: 'System003',
    SYSTEM_FOUR: 'System004',
    SYSTEM_FIVE: 'System005',
    SYSTEM_SIX: 'System006',
    BDT: 'BDT',
}


export const deviceTypes = [Constants.DESKTOP, Constants.MOBILE, Constants.TABLET, Constants.OTHERS]





export const segmentArray = [
    "marketingCareer",
    "marketingFlight",
    "operatingCareer",
    "operatingFlight",
    "departure",
    "departureDateTime",
    "arrival",
    "arrivalDateTime",
    "bookingCode"

];




